version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    # ports:
    #   - 8501:8501 # Uncomment this if App is not reachable

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:clickhouse

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2.11
    hostname: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # Add "forwardPorts": ["8123"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  clickhouse_data: